version: '3.2'

services:
  dbserver:
    container_name: dbserver
    build: docker/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=production
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=production
      - MYSQL_PASSWORD=production
    ports:
      - "53306:3306"
    volumes:
      - "db:/var/lib/mysql/data/"
    networks:
      - backend
  admin:
    image: adminer    
    ports:
      - "58080:8080"
    networks:
      - backend
  redis:
    container_name: redis
    image: redis
    ports:
      - "56379:6379"
    networks:
      - backend
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - 8001:8001
    volumes:
      - ./redisinsight:/db
    networks:
      - backend
  appserver:
    container_name: appserver
    image: web-app
    expose:
      - 8090
    ports:
      - "58888:8090"
    restart: always
    tty: true
    depends_on:
      - dbserver
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      JAVA_OPTS: ${JAVA_OPTS}
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS}
      MYSQL_HOST: dbserver
      MYSQL_PORT: 3306
      MYSQL_USERNAME: production
      MYSQL_PASSWORD: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CALC_HOST: calculator
      CALC_PORT: 6565
    networks:
      - backend
  calculator:
    container_name: calculator
    image: calculator
    restart: always
    tty: true
    depends_on:
      - dbserver
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      JAVA_OPTS: ${JAVA_OPTS}
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS}
      MYSQL_HOST: dbserver
      MYSQL_PORT: 3306
      MYSQL_USERNAME: production
      MYSQL_PASSWORD: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CALC_HOST: calculator
      CALC_PORT: 6565
    networks:
      - backend
networks:
  backend:
volumes:
  db:
    external: false