version: '3.7'

services:

  nginx:
    container_name: nginx
    build: docker/nginx
    restart: always
    ports:
      - "80:8080"
    networks: 
      - backend

  dbserver:
    container_name: dbserver
    build: docker/mysql
    restart: always
    environment:
      MYSQL_DATABASE: production
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: production
      MYSQL_PASSWORD: production
    expose:
      - 3306
    networks: 
      - backend

  admin:    
    image: adminer    
    ports:
      - "58080:8080"
    networks: 
      - backend

  appserver:
    container_name: appserver
    restart: always
    build: docker/springboot-prod
    expose:
      - 8090
    depends_on: 
      - dbserver
    tty: true
    environment:
      spring.profiles.active: "prod"
    networks: 
      - backend

networks:
  backend:

  