# ----------------------------------------
# DB PROPERTIES
# ----------------------------------------
  datasource:
    url: jdbc:postgresql://localhost:5432/test0
    username: test0
    password: test
    driverClassName: org.postgresql.Driver