# ----------------------------------------
# SECURITY PROPERTIES
# ----------------------------------------
spring:
  security:
    user:
      name: user
      password: root
# ----------------------------------------
# DB PROPERTIES
# ----------------------------------------
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/portfolio_management
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver