# ----------------------------------------
# LOCAL VERSION PROPERTIES
# ----------------------------------------
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/app_dev_db?verifyServerCertificate=false&useSSL=false
    username: app-dev
    password: app_dev
    driverClassName: com.mysql.jdbc.Driver
    initialization-mode: never
  jpa: 
    hibernate: 
      ddl-auto: none
  flywayMigrate:
    url: jdbc:mysql://127.0.0.1:3306/app_dev_db?verifyServerCertificate=false&useSSL=false
    username: app-dev
    password: app_dev
  devtools:
     restart:
       enabled: true
     remote:
       secret: spring-remote
