# ----------------------------------------
# DEFAULT VERSION PROPERTIES
# ----------------------------------------
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DATABSE:production}?verifyServerCertificate=false&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:production}
    password: ${MYSQL_PASSWORD:production}
    driverClassName: com.mysql.jdbc.Driver
    initialization-mode: never
  cache:
    jcache:
      config: classpath:ehcache.xml
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        generate_statistics: false
        order_inserts: true
        format_sql: true
        jdbc:
          batch_size: 500
  session:
    store-type: redis
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  devtools:
    restart:
      enabled: true
      exclude: META-INF/maven/**,META-INF/resources/**,resources/**,static/**,public/**,templates/**,**/*Test.class,**/*Tests.class,git.properties,META-INF/build-info.properties
      log-condition-evaluation-delta: true
      poll-interval: 5s
      quiet-period: 400ms
    remote:
      secret: spring-remote
server:
  port : 58080
  shutdown: graceful
calculator:
  work-stealing-parallelism: ${AVAILABLE_PROCESSOR_NUM:2}
  thread-pool-executor:
    core-pool-size: ${CORE_POOL_SIZE:5}
    max-pool-size: ${MAX_POOL_SIZE:10}
    queue-capacity: ${QUEUE_CAPACITY:25}

