# ----------------------------------------
# LOCAL ACTIVE MODE
# ----------------------------------------
spring:
  profiles:
    active: local
  cache:
    jcache:
      config: classpath:ehcache.xml
  lifecycle:
    timeout-per-shutdown-phase: 20s
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
grpc:
  enable-reflection: true