/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project.calculator;

import org.junit.jupiter.api.Test;

class CalculationServerMainTest {

    @Test
    void test() {}
}
