# ----------------------------------------
# DEFAULT ACTIVE MODE
# ----------------------------------------
spring:
  profiles:
    active: local
  lifecycle:
    timeout-per-shutdown-phase: 20s
logging: 
  level: 
    org: 
      hibernate: 
        SQL: DEBUG
        type: 
          descriptor:
            sql:
              BasicBinder: TRACE
server:
  shutdown: graceful
