CREATE TABLE portfolio_management.USER_MASTER (
    USER_ID VARCHAR(8) NOT NULL,
    VERSION INTEGER(10) NOT NULL,
    USER_NAME VARCHAR(300) NOT NULL,
    PASSWORD VARCHAR(30) NOT NULL,
    USER_AUTHENTICATION VARCHAR(200) DEFAULT 'UNDEFINED',
    IS_DELETED BOOLEAN DEFAULT 0,
    IS_LOCKED BOOLEAN DEFAULT 0,
    PRIMARY KEY (USER_ID , VERSION)
)