CREATE TABLE bond_master (
    BOND_CODE VARCHAR(50) NOT NULL,
    VERSION INTEGER(10) DEFAULT 0,
    BOND_NAME VARCHAR(300) NOT NULL,
    ISSUE_DATE DATE NOT NULL,
    MATURITY DATE NOT NULL,
    COUPON_RATE DECIMAL(8 , 8 ) NOT NULL,
    PAYMENT_TYPE VARCHAR(50) NOT NULL,
    UNIT DECIMAL(10 , 0 ) NOT NULL,
    FACE_VALUE DECIMAL(25 , 12 ) NOT NULL,
    ISSUER_SECTOR_CODE CHAR(5) NOT NULL,
    IS_DELETED BOOLEAN DEFAULT 0,
    PRIMARY KEY (BOND_CODE , VERSION)
)