/*
-- Query: SELECT * FROM app_dev_db.currency_master
LIMIT 0, 1000

-- Date: 2019-12-09 21:36
*/
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('061','AED','ＵＡＥ　ディルハム','147');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('025','AFA','アフガニスタン　アフガニ','130');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('070','ARA','アルゼンチン　アストラル','413');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('016','AUD','オーストラリア　ドル','601');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('026','BDT','バングラディシュ　タカ','127');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('079','BGP','エジプト　ポンド','506');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('052','BHD','バハレーン　ディナール','135');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('071','BOB','ボリビア　ボリビアーノ','408');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('072','BRL','ブラジル　レアル','410');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('003','CAD','カナダ　ドル','302');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('028','CAR','カンボジア　リヤル','120');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('073','CLP','チリ　ペソ','409');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('017','CNY','人民元','105');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('074','COP','コロンビア　ペソ','401');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('011','DKK','デンマーク　クローネ','204');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('078','DZD','アルジェリア　ディナール','504');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('089','EUR','ユーロ','600');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('002','GBP','イギリス　ポンド','205');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('081','GHC','ガーナ　セディ','517');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('019','HKD','香港ドル','108');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('030','IDR','インドネシア　ルピー','118');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('029','INR','インド　ルピー','123');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('054','IQD','イラク　ディナール','134');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('053','IRR','イラン　リヤル','133');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('015','JPY','円','192');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('082','KES','ケニア　シリング','541');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('037','KRW','韓国ウォン','103');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('055','KWD','クウェート　ディナール','138');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('031','LAK','ラオス　キャブ','121');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('038','LKR','スリランカ　ルピー','125');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('083','LYD','リビア　ディナール','505');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('084','MAD','モロッコ　だーラム','501');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('088','MXN','メキシコ　ペソ','305');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('027','MYK','ミヤンマーク　ヤット','122');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('032','MYR','マレーシア　リンギッド','113');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('085','NGN','ナイジェリア　ナイラ','524');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('033','NPR','ネパール　ルピー','131');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('018','NZD','ニュージランド　ドル','606');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('056','OMR','オマーン　リヤル','141');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('075','PEI','ペルー　インティ','407');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('035','PGK','パブアニュギニア　キナ','602');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('036','PHP','フィリピン　ペソ','117');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('034','PKR','パキスタン　ルピー','124');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('063','PYG','パラグアイ　グアラーニ','411');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('057','QAR','カタール　リヤル','140');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('058','SAR','サウジアラビア　リヤル','137');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('006','SEK','スウエーデン　クローネ','203');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('020','SGD','シンガポール　ドル','112');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('049','SUR','ロシア　ルーブル','224');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('059','SYP','シリア・アラブ　ポンド','145');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('040','THB','タイ　バーツ','111');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('060','TRL','トルコ　リラ','234');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('039','TWD','台湾ドル','106');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('001','USD','アメリカ　ドル','304');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('076','UYP','ウルグアイ　ペソ','412');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('077','VEB','ベネズエラ　ボリバール','402');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('041','VND','ベトナム　ドン','110');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('090','XXX','その他通貨','999');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('086','ZAR','南アフリカ　ランド','551');
INSERT INTO `currency_master` (`CURRENCY_ID`,`CURRENCY_CODE`,`CURRENCY_NAME`,`COUNTRY_CODE`) VALUES ('087','ZWD','ジンバブエ　ドル','549');
