/*
-- Query: SELECT * FROM portfolio_management.user_master
-- Date: 2019-07-12 14:23
*/
INSERT INTO `user_master` (`USER_ID`,`VERSION`,`USER_NAME`,`PASSWORD`,`USER_AUTHENTICATION`,`IS_DELETED`,`IS_LOCKED`) VALUES (1,0,'root1','rootroot','ADMIN',0,0);
INSERT INTO `user_master` (`USER_ID`,`VERSION`,`USER_NAME`,`PASSWORD`,`USER_AUTHENTICATION`,`IS_DELETED`,`IS_LOCKED`) VALUES (2,0,'root2','rootroot','ADMIN',1,0);
INSERT INTO `user_master` (`USER_ID`,`VERSION`,`USER_NAME`,`PASSWORD`,`USER_AUTHENTICATION`,`IS_DELETED`,`IS_LOCKED`) VALUES (3,0,'root3','rootroot','ADMIN',0,1);
INSERT INTO `user_master` (`USER_ID`,`VERSION`,`USER_NAME`,`PASSWORD`,`USER_AUTHENTICATION`,`IS_DELETED`,`IS_LOCKED`) VALUES (4,0,'root4','rootroot','ADMIN',0,0);
INSERT INTO `user_master` (`USER_ID`,`VERSION`,`USER_NAME`,`PASSWORD`,`USER_AUTHENTICATION`,`IS_DELETED`,`IS_LOCKED`) VALUES (5,1,'root5','rootroot','ADMIN',0,0);
INSERT INTO `user_master` (`USER_ID`,`VERSION`,`USER_NAME`,`PASSWORD`,`USER_AUTHENTICATION`,`IS_DELETED`,`IS_LOCKED`) VALUES (6,0,'GENERAL1','GENERALl','GENERAL',0,0);
INSERT INTO `user_master` (`USER_ID`,`VERSION`,`USER_NAME`,`PASSWORD`,`USER_AUTHENTICATION`,`IS_DELETED`,`IS_LOCKED`) VALUES (7,0,'GENERAL2','GENERALl','GENERAL',1,0);
INSERT INTO `user_master` (`USER_ID`,`VERSION`,`USER_NAME`,`PASSWORD`,`USER_AUTHENTICATION`,`IS_DELETED`,`IS_LOCKED`) VALUES (8,0,'GENERAL3','GENERALl','GENERAL',0,1);
INSERT INTO `user_master` (`USER_ID`,`VERSION`,`USER_NAME`,`PASSWORD`,`USER_AUTHENTICATION`,`IS_DELETED`,`IS_LOCKED`) VALUES (9,0,'GENERAL4','GENERALl','GENERAL',0,0);
INSERT INTO `user_master` (`USER_ID`,`VERSION`,`USER_NAME`,`PASSWORD`,`USER_AUTHENTICATION`,`IS_DELETED`,`IS_LOCKED`) VALUES (10,1,'GENERAL5','GENERALl','GENERAL',0,0);
INSERT INTO `user_master` (`USER_ID`,`VERSION`,`USER_NAME`,`PASSWORD`,`USER_AUTHENTICATION`,`IS_DELETED`,`IS_LOCKED`) VALUES (11,0,'GENERAL6','GENERALl','UNDEFINED',0,0);
