/*
-- Query: SELECT * FROM portfolio_management.user_master
-- Date: 2019-07-12 14:23
*/
INSERT INTO `user_master` (`USER_ID`,`VERSION`,`USER_NAME`,`PASSWORD`,`USER_AUTHENTICATION`,`IS_DELETED`,`IS_LOCKED`) VALUES ('U10001',0,'root','rootroot','ADMIN',0,0);
INSERT INTO `user_master` (`USER_ID`,`VERSION`,`USER_NAME`,`PASSWORD`,`USER_AUTHENTICATION`,`IS_DELETED`,`IS_LOCKED`) VALUES ('U10002',0,'root','rootroot','ADMIN',1,0);
INSERT INTO `user_master` (`USER_ID`,`VERSION`,`USER_NAME`,`PASSWORD`,`USER_AUTHENTICATION`,`IS_DELETED`,`IS_LOCKED`) VALUES ('U10003',0,'root','rootroot','ADMIN',0,1);
INSERT INTO `user_master` (`USER_ID`,`VERSION`,`USER_NAME`,`PASSWORD`,`USER_AUTHENTICATION`,`IS_DELETED`,`IS_LOCKED`) VALUES ('U10004',0,'root','rootroot','ADMIN',0,0);
INSERT INTO `user_master` (`USER_ID`,`VERSION`,`USER_NAME`,`PASSWORD`,`USER_AUTHENTICATION`,`IS_DELETED`,`IS_LOCKED`) VALUES ('U10005',1,'root','rootroot','ADMIN',0,0);
INSERT INTO `user_master` (`USER_ID`,`VERSION`,`USER_NAME`,`PASSWORD`,`USER_AUTHENTICATION`,`IS_DELETED`,`IS_LOCKED`) VALUES ('U10006',0,'GENERAL','GENERALl','GENERAL',0,0);
INSERT INTO `user_master` (`USER_ID`,`VERSION`,`USER_NAME`,`PASSWORD`,`USER_AUTHENTICATION`,`IS_DELETED`,`IS_LOCKED`) VALUES ('U10007',0,'GENERAL','GENERALl','GENERAL',1,0);
INSERT INTO `user_master` (`USER_ID`,`VERSION`,`USER_NAME`,`PASSWORD`,`USER_AUTHENTICATION`,`IS_DELETED`,`IS_LOCKED`) VALUES ('U10008',0,'GENERAL','GENERALl','GENERAL',0,1);
INSERT INTO `user_master` (`USER_ID`,`VERSION`,`USER_NAME`,`PASSWORD`,`USER_AUTHENTICATION`,`IS_DELETED`,`IS_LOCKED`) VALUES ('U10009',0,'GENERAL','GENERALl','GENERAL',0,0);
INSERT INTO `user_master` (`USER_ID`,`VERSION`,`USER_NAME`,`PASSWORD`,`USER_AUTHENTICATION`,`IS_DELETED`,`IS_LOCKED`) VALUES ('U10010',1,'GENERAL','GENERALl','GENERAL',0,0);
INSERT INTO `user_master` (`USER_ID`,`VERSION`,`USER_NAME`,`PASSWORD`,`USER_AUTHENTICATION`,`IS_DELETED`,`IS_LOCKED`) VALUES ('U10011',0,'GENERAL','GENERALl','UNDEFINED',0,0);
