/*
-- Query: SELECT * FROM portfolio_management.USER_MASTER
-- Date: 2019-07-12 14:23
*/
INSERT INTO `USER_MASTER` (`USER_ID`,`VERSION`,`USER_NAME`,`PASSWORD`,`USER_AUTHENTICATION`,`IS_DELETED`,`IS_LOCKED`) VALUES ('U10001',0,'root','rootroot','admin',0,0);
INSERT INTO `USER_MASTER` (`USER_ID`,`VERSION`,`USER_NAME`,`PASSWORD`,`USER_AUTHENTICATION`,`IS_DELETED`,`IS_LOCKED`) VALUES ('U10002',0,'root','rootroot','admin',1,0);
INSERT INTO `USER_MASTER` (`USER_ID`,`VERSION`,`USER_NAME`,`PASSWORD`,`USER_AUTHENTICATION`,`IS_DELETED`,`IS_LOCKED`) VALUES ('U10003',0,'root','rootroot','admin',0,1);
INSERT INTO `USER_MASTER` (`USER_ID`,`VERSION`,`USER_NAME`,`PASSWORD`,`USER_AUTHENTICATION`,`IS_DELETED`,`IS_LOCKED`) VALUES ('U10004',0,'root','rootroot','admin',0,0);
INSERT INTO `USER_MASTER` (`USER_ID`,`VERSION`,`USER_NAME`,`PASSWORD`,`USER_AUTHENTICATION`,`IS_DELETED`,`IS_LOCKED`) VALUES ('U10005',1,'root','rootroot','admin',0,0);
INSERT INTO `USER_MASTER` (`USER_ID`,`VERSION`,`USER_NAME`,`PASSWORD`,`USER_AUTHENTICATION`,`IS_DELETED`,`IS_LOCKED`) VALUES ('U10006',0,'general','generall','general',0,0);
INSERT INTO `USER_MASTER` (`USER_ID`,`VERSION`,`USER_NAME`,`PASSWORD`,`USER_AUTHENTICATION`,`IS_DELETED`,`IS_LOCKED`) VALUES ('U10007',0,'general','generall','general',1,0);
INSERT INTO `USER_MASTER` (`USER_ID`,`VERSION`,`USER_NAME`,`PASSWORD`,`USER_AUTHENTICATION`,`IS_DELETED`,`IS_LOCKED`) VALUES ('U10008',0,'general','generall','general',0,1);
INSERT INTO `USER_MASTER` (`USER_ID`,`VERSION`,`USER_NAME`,`PASSWORD`,`USER_AUTHENTICATION`,`IS_DELETED`,`IS_LOCKED`) VALUES ('U10009',0,'general','generall','general',0,0);
INSERT INTO `USER_MASTER` (`USER_ID`,`VERSION`,`USER_NAME`,`PASSWORD`,`USER_AUTHENTICATION`,`IS_DELETED`,`IS_LOCKED`) VALUES ('U10010',1,'general','generall','general',0,0);
INSERT INTO `USER_MASTER` (`USER_ID`,`VERSION`,`USER_NAME`,`PASSWORD`,`USER_AUTHENTICATION`,`IS_DELETED`,`IS_LOCKED`) VALUES ('U10011',0,'general','generall','undefined',0,0);
