CREATE TABLE currency_master (
    CURRENCY_ID   CHAR(5) NOT NULL,
    CURRENCY_CODE   CHAR(5) NOT NULL,
    CURRENCY_NAME VARCHAR(500) NOT NULL,
    COUNTRY_CODE CHAR(5) NOT NULL, 
    PRIMARY KEY (CURRENCY_CODE)
)