/*
-- Query: SELECT * FROM app_dev_db.user_master
-- Date: 2020-01-01 13:46
*/
truncate table user_master;
INSERT INTO `user_master` (`USER_ID`,`VERSION`,`USER_NAME`,`ENCODED_PASSWORD`,`USER_AUTHENTICATION`,`IS_DELETED`,`IS_LOCKED`,`MAIL_ADDRESS`) VALUES (1,0,'root_user1','$2a$10$BQ1OVcmKcoc9VSiqY9A56.m95od6AB.C25NBsjEGlEro/oyxq5nNG','ADMIN',0,0,'root-user01@example.com');
INSERT INTO `user_master` (`USER_ID`,`VERSION`,`USER_NAME`,`ENCODED_PASSWORD`,`USER_AUTHENTICATION`,`IS_DELETED`,`IS_LOCKED`,`MAIL_ADDRESS`) VALUES (2,0,'root_user2','$2a$10$oQNHLkCu8dE48/TXlSSbhOQEZuRM3aHmb/YbnjzN0VKs/SI4cTGLO','ADMIN',1,0,'root-user02@example.com');
INSERT INTO `user_master` (`USER_ID`,`VERSION`,`USER_NAME`,`ENCODED_PASSWORD`,`USER_AUTHENTICATION`,`IS_DELETED`,`IS_LOCKED`,`MAIL_ADDRESS`) VALUES (3,0,'root_user3','$2a$10$S0BPwPX3l9jgP73G6ny0geVwI9.vz5xmOq47V/eohFKGHiFqkyFMi','ADMIN',0,1,'root-user03@example.com');
INSERT INTO `user_master` (`USER_ID`,`VERSION`,`USER_NAME`,`ENCODED_PASSWORD`,`USER_AUTHENTICATION`,`IS_DELETED`,`IS_LOCKED`,`MAIL_ADDRESS`) VALUES (4,0,'root_user4','$2a$10$swYfEbiAbt27TodjIDs4.uLDrLqNjyXmv3yHAOv4Vq7YBP7BIPs0G','ADMIN',0,0,'root-user04@example.com');
INSERT INTO `user_master` (`USER_ID`,`VERSION`,`USER_NAME`,`ENCODED_PASSWORD`,`USER_AUTHENTICATION`,`IS_DELETED`,`IS_LOCKED`,`MAIL_ADDRESS`) VALUES (5,1,'root_user5','$2a$10$rIRBwhX61DWTk/njHFqpMet3E2q3xHM44Pn8JEK1y7xnIyqXlXe.q','ADMIN',0,0,'root-user05@example.com');
INSERT INTO `user_master` (`USER_ID`,`VERSION`,`USER_NAME`,`ENCODED_PASSWORD`,`USER_AUTHENTICATION`,`IS_DELETED`,`IS_LOCKED`,`MAIL_ADDRESS`) VALUES (6,0,'general_user1','$2a$10$2nr1y382vTJ75kI8Q61SFuMTLzbqrCrakjiEANw22.ZsIzZDr6NWa','GENERAL',0,0,'general-user01@example.com');
INSERT INTO `user_master` (`USER_ID`,`VERSION`,`USER_NAME`,`ENCODED_PASSWORD`,`USER_AUTHENTICATION`,`IS_DELETED`,`IS_LOCKED`,`MAIL_ADDRESS`) VALUES (7,0,'general_user2','$2a$10$RxJUicKqJSFtgUAVpSoMo.pRP5raXNb5nJPOTpPlAWpowWg4UYRYG','GENERAL',1,0,'general-user02@example.com');
INSERT INTO `user_master` (`USER_ID`,`VERSION`,`USER_NAME`,`ENCODED_PASSWORD`,`USER_AUTHENTICATION`,`IS_DELETED`,`IS_LOCKED`,`MAIL_ADDRESS`) VALUES (8,0,'general_user3','$2a$10$xWKmO/P0HD4cgFTjUWxOUuIWMpSpcvWPs82ajyaqI1Chh85lWepEK','GENERAL',0,1,'general-user03@example.com');
INSERT INTO `user_master` (`USER_ID`,`VERSION`,`USER_NAME`,`ENCODED_PASSWORD`,`USER_AUTHENTICATION`,`IS_DELETED`,`IS_LOCKED`,`MAIL_ADDRESS`) VALUES (9,0,'general_user4','$2a$10$SSG088NG8m8WGoWsTb9HrOVr7Nbxne12abzczbrcxPefWkkgK2oeq','GENERAL',0,0,'general-user04@example.com');
INSERT INTO `user_master` (`USER_ID`,`VERSION`,`USER_NAME`,`ENCODED_PASSWORD`,`USER_AUTHENTICATION`,`IS_DELETED`,`IS_LOCKED`,`MAIL_ADDRESS`) VALUES (10,1,'general_user5','$2a$10$fIZl57e2mQ9Lj7ka9Tnn6ez5./piuRT2bcFSW83WjZ8ksfrmjBlXW','GENERAL',0,0,'general-user05@example.com');
INSERT INTO `user_master` (`USER_ID`,`VERSION`,`USER_NAME`,`ENCODED_PASSWORD`,`USER_AUTHENTICATION`,`IS_DELETED`,`IS_LOCKED`,`MAIL_ADDRESS`) VALUES (11,0,'general_user6','$2a$10$Zl8093l2zKtac7fNXXuRgureEqLILPfGCY8QCWuU019Tbffu5G3oq','UNDEFINED',0,0,'general-user06@example.com');
